"use client";
import Image from "next/image";
import { useState, useEffect, useRef, useTransition } from "react";
import { Home, MessagesSquare, BookOpen, X, Search, ArrowLeft, Send, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useFocusTrap, useEscape } from "@/components/ui/drawer";
import { getSupportMessages, sendSupportMessage } from "@/lib/support/actions";
import { HELP_CATEGORIES } from "@/lib/support/help";

type Ticket = Awaited<ReturnType<typeof getSupportMessages>>[number];
export function SupportBubble() {
 const [open,setOpen]=useState(false); const [tab,setTab]=useState("home");
 const [search,setSearch]=useState(""); const [category,setCategory]=useState<number|null>(null); const [article,setArticle]=useState<{title:string;body:string}|null>(null);
 const [tickets,setTickets]=useState<Ticket[]>([]); const [ticket,setTicket]=useState<string|undefined>(); const [compose,setCompose]=useState(false); const [body,setBody]=useState(""); const [error,setError]=useState(""); const [pending,start]=useTransition();
 const ref=useRef<HTMLDivElement>(null); useFocusTrap(ref,open); useEscape(open,()=>setOpen(false));
 useEffect(()=>{ function show(){setOpen(true);setTab("messages");setCompose(true);} window.addEventListener("clientturn:support",show); return()=>window.removeEventListener("clientturn:support",show); },[]);
 useEffect(()=>{ if(!open || tab!=="messages")return; let active=true; getSupportMessages().then(rows=>{if(active)setTickets(rows);}).catch(()=>{if(active)setError("Could not load your support conversations.");}); return()=>{active=false;}; },[open,tab]);
 const selected=tickets.find(t=>t.id===ticket);
 return <><button aria-label="Open ClientTurn support" aria-expanded={open} aria-controls="clientturn-support" onClick={()=>setOpen(!open)} className="fixed bottom-5 right-5 z-40 flex size-14 items-center justify-center rounded-full border-2 border-[var(--ct-lime)] bg-white shadow-lg ring-1 ring-[#0B1020] transition-transform hover:scale-105 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-content-accent"><Image src="/icon.png" alt="" width={32} height={32} /></button>{open && <div id="clientturn-support" ref={ref} role="dialog" aria-label="ClientTurn support" className="fixed bottom-22 right-3 z-50 flex h-[min(650px,calc(100dvh-110px))] w-[min(400px,calc(100vw-24px))] flex-col overflow-hidden rounded-2xl border border-line bg-white text-content shadow-2xl"><header className="flex shrink-0 items-center justify-between border-b border-line px-5 py-4"><Image src="/white_background_logo.png" alt="ClientTurn support" width={138} height={46} /><button aria-label="Close support" className="flex size-10 items-center justify-center rounded-full hover:bg-bg" onClick={()=>setOpen(false)}><X className="size-5" /></button></header><div className="flex-1 overflow-y-auto p-5">
 {tab==="home" && <div className="space-y-5"><div className="rounded-xl bg-[#0B1020] p-6 text-white"><p className="text-sm text-[#B7F34A]">Here for your next step</p><h2 className="mt-3 text-2xl font-semibold">Hello. How can we help?</h2><p className="mt-3 text-sm text-white/75">Get to know ClientTurn, find an answer or leave our team a message.</p></div><button onClick={()=>{setTab("messages");setCompose(true);}} className="flex w-full items-center justify-between rounded-xl border border-line p-4 text-left"><span><strong className="text-sm">Send us a message</strong><span className="mt-1 block text-xs text-content-muted">Keep your support conversation here.</span></span><Send className="size-4 text-content-accent" /></button>{HELP_CATEGORIES.map((c,i)=><button key={c.title} onClick={()=>{setTab("help");setCategory(i);}} className="block w-full border-b border-line pb-4 text-left"><h3 className="text-sm font-semibold">{c.title}</h3><p className="mt-1 text-sm text-content-muted">{c.description}</p></button>)}</div>}
 {tab==="messages" && <div className="space-y-4">{selected || compose ? <><button className="flex items-center gap-2 text-sm text-content-muted" onClick={()=>{setTicket(undefined);setCompose(false);}}><ArrowLeft className="size-4" />All messages</button><h2 className="font-semibold">{selected ? `${selected.reference} · ${selected.subject}` : "Send us a message"}</h2>{selected?.support_messages.slice().sort((a,b)=>a.created_at.localeCompare(b.created_at)).map(m=><div key={m.id} className={`rounded-xl p-3 text-sm ${m.direction==="INBOUND" ? "ml-5 bg-bg" : "mr-5 border border-line"}`}><p className="mb-1 text-xs text-content-muted">{m.direction==="INBOUND" ? "You" : "ClientTurn support"}</p><p className="whitespace-pre-wrap">{m.body}</p></div>)}<label className="block text-sm font-medium">Your message<textarea value={body} maxLength={5000} onChange={e=>setBody(e.target.value)} className="mt-2 min-h-28 w-full rounded-lg border border-line-strong p-3 text-sm" placeholder="Tell us what you need help with…" /></label><Button fullWidth loading={pending} disabled={body.trim().length<5} onClick={()=>start(async()=>{try{const result=await sendSupportMessage({body,ticketId:ticket});if(result.error){setError(result.error);return;}setBody("");setError("");setCompose(false);setTicket(undefined);setTickets(await getSupportMessages());}catch{setError("Could not send your message. Please try again.");}})}><Send className="size-4" />Send message</Button><p className="text-xs text-content-muted">Your message is saved to the support queue. Replies appear here.</p></> : <><h2 className="text-lg font-semibold">Your conversations</h2><Button fullWidth onClick={()=>setCompose(true)}>Send us a message</Button>{tickets.map(t=><button key={t.id} onClick={()=>setTicket(t.id)} className="w-full rounded-lg border border-line p-4 text-left"><p className="text-xs text-content-muted">{t.reference} · {t.status.toLowerCase()}</p><p className="mt-1 text-sm font-medium">{t.subject}</p></button>)}{!tickets.length && <p className="py-8 text-center text-sm text-content-muted">Your support conversations will appear here.</p>}</>}{error&&<p role="alert" className="text-sm text-danger-600">{error}</p>}</div>}
 {tab==="help" && <div className="space-y-4"><label className="relative block"><Search className="absolute left-3 top-3 size-4 text-content-muted" /><input aria-label="Search help articles" value={search} onChange={e=>{setSearch(e.target.value);setArticle(null);setCategory(null);}} placeholder="Search for answers…" className="w-full rounded-lg border border-line-strong py-2.5 pl-9 pr-3 text-sm" /></label>{article ? <><button onClick={()=>setArticle(null)} className="flex items-center gap-2 text-sm text-content-muted"><ArrowLeft className="size-4" />Back</button><h2 className="text-lg font-semibold">{article.title}</h2><p className="text-sm leading-7 text-content-secondary">{article.body}</p></> : category!==null ? <><button onClick={()=>setCategory(null)} className="text-sm text-content-muted">← All categories</button><h2 className="font-semibold">{HELP_CATEGORIES[category].title}</h2>{HELP_CATEGORIES[category].articles.map(a=><button className="flex w-full justify-between border-b border-line py-4 text-left text-sm" key={a.title} onClick={()=>setArticle(a)}>{a.title}<ChevronRight className="size-4" /></button>)}</> : search ? <>{HELP_CATEGORIES.flatMap(c=>c.articles).filter(a=>`${a.title} ${a.body}`.toLowerCase().includes(search.toLowerCase())).map(a=><button key={a.title} onClick={()=>setArticle(a)} className="block w-full border-b border-line py-4 text-left text-sm">{a.title}</button>)}{!HELP_CATEGORIES.flatMap(c=>c.articles).some(a=>`${a.title} ${a.body}`.toLowerCase().includes(search.toLowerCase()))&&<p className="text-sm text-content-muted">No articles found. Try another search or send us a message.</p>}</> : HELP_CATEGORIES.map((c,i)=><button key={c.title} onClick={()=>setCategory(i)} className="w-full rounded-xl border border-line p-4 text-left"><h2 className="text-sm font-semibold">{c.title}</h2><p className="mt-1 text-sm text-content-muted">{c.description}</p><p className="mt-3 text-xs text-content-muted">{c.articles.length} articles</p></button>)}</div>}
 </div><nav aria-label="Support sections" className="grid shrink-0 grid-cols-3 border-t border-line bg-white">{[{id:"home",label:"Home",Icon:Home},{id:"messages",label:"Messages",Icon:MessagesSquare},{id:"help",label:"Help",Icon:BookOpen}].map(({id,label,Icon})=><button key={id} aria-current={tab===id?"page":undefined} onClick={()=>{setTab(id);setError("");}} className={`flex flex-col items-center gap-1 py-3 text-xs ${tab===id?"text-content-accent":"text-content-muted"}`}><Icon className="size-5" />{label}</button>)}</nav></div>}</>;
}
