"""
Builds the UK SIC taxonomy migration from the ONS source files.

Sources (ONS, "UK SIC: 2026", files dated 3 Aug 2026 — see
docs/revenue-engine/01-evidence-register.md §1):
  scripts/data/sic/uksic2026summaryofstructure03aug2026.xlsx
  scripts/data/sic/uksic2007to2026correspondence03aug2026.xlsx

Usage:  python scripts/build-sic-taxonomy.py <output.sql>

Codes are stored two ways:
  * `code`         — the ONS dotted form: section "K", division "62", group
                     "62.1", class "62.12", subclass "62.12/1".
  * `numeric_code` — the five-digit form Companies House uses for class and
                     subclass rows ("62120", "62121"), so a company's register
                     SIC matches without conversion. Null above class level.

SIC 2007 rows are taken from the correspondence table (every 2007 class and
subclass that maps to 2026), because Companies House filings still use 2007.
"""

import sys
import openpyxl

SUMMARY = "scripts/data/sic/uksic2026summaryofstructure03aug2026.xlsx"
CORRESPONDENCE = "scripts/data/sic/uksic2007to2026correspondence03aug2026.xlsx"


def sql(value):
    if value is None:
        return "null"
    return "'" + str(value).replace("'", "''").strip() + "'"


def clean(value):
    if value is None:
        return None
    text = str(value).strip()
    return None if text in ("", "na", "N/a") else text


def dotted_from_digits(digits):
    """'62' -> '62', '621' -> '62.1', '6212' -> '62.12', '62121' -> '62.12/1'."""
    if len(digits) <= 2:
        return digits
    if len(digits) == 3:
        return f"{digits[:2]}.{digits[2]}"
    if len(digits) == 4:
        return f"{digits[:2]}.{digits[2:]}"
    return f"{digits[:2]}.{digits[2:4]}/{digits[4]}"


def dotted_2007(value):
    """Correspondence cells are sometimes floats (62.13). Normalise to text."""
    if isinstance(value, float):
        return f"{value:.2f}"
    return str(value).strip()


def numeric_from_dotted(code):
    """'62.12' -> '62120'; '62.12/1' -> '62121'. Class and subclass only."""
    if "/" in code:
        base, sub = code.split("/")
        return base.replace(".", "") + sub
    digits = code.replace(".", "")
    return digits + "0" if len(digits) == 4 else None


def level_of(code):
    if code.isalpha():
        return "SECTION"
    if "/" in code:
        return "SUBCLASS"
    digits = code.replace(".", "")
    return {2: "DIVISION", 3: "GROUP", 4: "CLASS"}[len(digits)]


def parent_of(code, section):
    level = level_of(code)
    if level == "SECTION":
        return None
    if level == "DIVISION":
        return section
    if level == "SUBCLASS":
        return code.split("/")[0]
    digits = code.replace(".", "")
    return dotted_from_digits(digits[:-1])


def main(out_path):
    rows_2026 = []
    wb = openpyxl.load_workbook(SUMMARY, read_only=True)
    for row in list(wb.worksheets[0].iter_rows(values_only=True))[1:]:
        title, section, division, group, klass, subclass = (clean(v) for v in row[:6])
        if not title or not section:
            continue
        deepest = subclass or klass or group or division
        code = section if deepest is None else dotted_from_digits(deepest)
        rows_2026.append((code, level_of(code), title, parent_of(code, section), section))

    rows_2007 = {}
    mappings = []
    wb = openpyxl.load_workbook(CORRESPONDENCE, read_only=True)
    for row in list(wb.worksheets[0].iter_rows(values_only=True))[1:]:
        code_2007, level_2007, title_2007, code_2026, _title_2026, kind = row[:6]
        if code_2007 is None or code_2026 is None:
            continue
        c07 = dotted_2007(code_2007)
        c26 = dotted_2007(code_2026)
        # 'N/a' marks a 2026 code with no 2007 predecessor: not a mapping.
        if c07 in ("N/a", "na") or c26 in ("N/a", "na"):
            continue
        if level_2007 in ("Class", "Subclass"):
            rows_2007[c07] = (c07, level_2007.upper(), str(title_2007).strip())
        mappings.append((c07, c26, clean(kind)))

    with open(out_path, "w", encoding="utf-8", newline="\n") as out:
        out.write("-- Generated by scripts/build-sic-taxonomy.py from ONS UK SIC 2026 files (3 Aug 2026).\n")
        out.write("-- Do not edit by hand; regenerate instead.\n\n")
        out.write("insert into public.industry_codes (system, code, numeric_code, level, title, parent_code, section) values\n")
        values = []
        for code, level, title, parent, section in rows_2026:
            numeric = numeric_from_dotted(code) if level in ("CLASS", "SUBCLASS") else None
            values.append(
                f"  ('uk_sic_2026', {sql(code)}, {sql(numeric)}, {sql(level)}, {sql(title)}, {sql(parent)}, {sql(section)})"
            )
        for code, level, title in rows_2007.values():
            values.append(
                f"  ('uk_sic_2007', {sql(code)}, {sql(numeric_from_dotted(code))}, {sql(level)}, {sql(title)}, null, null)"
            )
        out.write(",\n".join(values))
        out.write("\non conflict (system, code) do update set title = excluded.title;\n\n")

        out.write("insert into public.industry_code_mappings (from_system, from_code, to_system, to_code, correspondence) values\n")
        out.write(
            ",\n".join(
                f"  ('uk_sic_2007', {sql(a)}, 'uk_sic_2026', {sql(b)}, {sql(k)})" for a, b, k in mappings
            )
        )
        out.write("\non conflict do nothing;\n")

    print(f"2026 rows: {len(rows_2026)}; 2007 rows: {len(rows_2007)}; mappings: {len(mappings)}")


if __name__ == "__main__":
    main(sys.argv[1])
